# Generated by Django 5.0.4 on 2024-07-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='author_id',
        ),
    ]
