# Generated by Django 5.0.4 on 2024-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPage', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='poster_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
